#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>//变长参数函数所需的头文件
#include "node.h"
#include "syntab.c"
#include "functype.c"
#include "struct.c"
#include "subnode.c"
#include "expcheck.c"
#include "innerCode.c"
#include "dstCode.c"